#Data Structure,Functions,NumPy,Pandas

##Section A: Data Structures & Control Structures

1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
# Create a list of 5 integers
the_list = [10, 20, 30, 40, 50]
print(f"Original list: {the_list}")

# 1. append(element): Adds an element to the end of the list.
the_list.append(60)
print(f"After append(60): {the_list}")

# 2. extend(iterable): Appends the elements of an iterable (like another list).
the_list.extend([70, 80])
print(f"After extend([70, 80]): {the_list}")

# 3. insert: Inserts an element at a specific position.
the_list.insert(1, 15) # Insert 15 at index 1
print(f"After insert(1, 15): {the_list}")

# 4. remove: Removes the first occurrence of a specific value.
the_list.remove(40)
print(f"After remove(40): {the_list}")

# 5. pop: Removes and returns the element at a specific index (or the last if no index is given).
popped_element = the_list.pop(0) # Remove element at index 0.
print(f"Popped element (at index 0): {popped_element}")
print(f"After pop(0): {the_list}")

# 6. index: Returns the index of the first occurrence of a value.
index_of_30 = the_list.index(30)
print(f"Index of 30: {index_of_30}")

# 7. count: Returns the number of times a value appears in the list.
the_list.insert(3, 30) # Insert another 30 to test count
count_of_30 = the_list.count(30)
print(f"List with another 30: {the_list}")
print(f"Count of 30: {count_of_30}")

# 8. sort(): Sorts the list in-place (ascending by default)
the_list.sort()
print(f"After sort(): {the_list}")

# 9. reverse(): Reverses the order of elements in the list in-place
the_list.reverse()
print(f"After reverse(): {the_list}")

# 10. clear(): Removes all elements from the list
the_list.clear()
print(f"After clear(): {the_list}")

Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(1, 15): [10, 15, 20, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 15, 20, 30, 50, 60, 70, 80]
Popped element (at index 0): 10
After pop(0): [15, 20, 30, 50, 60, 70, 80]
Index of 30: 2
List with another 30: [15, 20, 30, 30, 50, 60, 70, 80]
Count of 30: 2
After sort(): [15, 20, 30, 30, 50, 60, 70, 80]
After reverse(): [80, 70, 60, 50, 30, 30, 20, 15]
After clear(): []


2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
# Create a tuple of 3 student names
stu_tuple = ('Mike', 'Hopper', 'Jane')
print(f"Original tuple: {stu_tuple}")

# Attempt to change the second name
try:
    stu_tuple[1] = 'Nancy'
except TypeError as e:
    print(f"Attempting to change the second name (stu_tuple[1] = 'Nancy') results in a:")
    print(f"Error: {e}")

# Explanation
print("Explanation:")
print("Tuples are 'immutable' data structures in Python.")
print("This means their contents 'cannot be changed' (modified, added, or removed) after they are created.")
print("The attempt to assign a new value to an element by its index results in a `TypeError: 'tuple' object does not support item assignment`.")

Original tuple: ('Mike', 'Hopper', 'Jane')
Attempting to change the second name (stu_tuple[1] = 'Nancy) results in a:
Error: 'tuple' object does not support item assignment
Explanation:
Tuples are 'immutable' data structures in Python.
This means their contents 'cannot be changed' (modified, added, or removed) after they are created.
The attempt to assign a new value to an element by its index results in a `TypeError: 'tuple' object does not support item assignment`.


3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
# Create a set of integers with duplicate values
set_of_duplicates = {1, 2, 3, 2, 4, 1, 5, 5, 3}
print(f"Set created with duplicates: {set_of_duplicates}")

# Explanation
print("Explanation:")
print("Sets in Python are an 'unordered collection of unique elements'.")
print("When a set is created, it automatically 'discards any duplicate values'.")
print("Therefore, even though the input included multiple instances of 1, 2, 3, and 5, the final printed set only contains each integer once, ensuring uniqueness: {1, 2, 3, 4, 5}.")


Set created with duplicates: {1, 2, 3, 4, 5}
Explanation:
Sets in Python are an 'unordered collection of unique elements'.
When a set is created, it automatically 'discards any duplicate values'.
Therefore, even though the input included multiple instances of 1, 2, 3, and 5, the final printed set only contains each integer once, ensuring uniqueness: {1, 2, 3, 4, 5}.


4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
# Create a dictionary
person = {
    'name': 'Chetu',
    'age': 20,
    'city': 'Davangere'
}
print(f"Original dictionary: {person}")

# 1. Update the age
person['age'] = 21
print(f"after updating age: {person}")

# 2. Add a new key 'email'
person['email'] = 'chetu.dvg@example.com'
print(f"after adding email: {person}")

# Print the final dictionary
print(f"Final dictionary: {person}")

Original dictionary: {'name': 'Chetu', 'age': 20, 'city': 'Davangere'}
after updating age: {'name': 'Chetu', 'age': 21, 'city': 'Davangere'}
after adding email: {'name': 'Chetu', 'age': 21, 'city': 'Davangere', 'email': 'chetu.dvg@example.com'}
Final dictionary: {'name': 'Chetu', 'age': 21, 'city': 'Davangere', 'email': 'chetu.dvg@example.com'}


5. Write a script that checks if a person is eligible to vote ($age \ge 18$). Take age as a variable and print the appropriate message.

In [ ]:
# Take age as a variable
age = 20

print(f"Checking eligibility for age: {age}")

# Check for voting eligibility
if age >= 18:
    print("You are 'eligible' to vote.")
else:
    print("You are 'not eligible' to vote.")

Checking eligibility for age: 20
You are 'eligible' to vote.


6. Given a 'marks' variable, print the grade:


* 90 and above: 'A'

* 75-89: 'B'

* 50-74: 'C'

* Below 50: 'Fail'





In [ ]:
# Define the marks variable
marks = 82

print(f"Marks obtained: {marks}")

if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'

print(f"The assigned grade is: '{grade}'")

Marks obtained: 82
The assigned grade is: 'B'


7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's
zero or negative.

In [ ]:
# Define the number variable
number = -4

print(f"Checking number: {number}")

if number > 0:
    # Check if positive number is also even
    if number % 2 == 0:
        print("The number is 'Positive and Even'.")
    else:
        print("The number is 'Positive and Odd'.")
elif number == 0:
    # If not positive, check if it is zero
    print("The number is 'Zero'.")
else:
    # If not positive and not zero, it must be negative
    print("The number is 'Negative'.")

Checking number: -4
The number is 'Negative'.


#Section B: Numpy

8. Create:

* A scalar using np.array(5)

* A 1D array with values 1 to 5

* A 2D array (2x3) with values from 10 to 60 in steps of 10




In [ ]:
import numpy as np

# A. Create a scalar
scalar = np.array(5)
print(f"A. Scalar:{scalar}")
print(f"   Shape: {scalar.shape}, Dimensions: {scalar.ndim}")

# B. A 1D array with values 1 to 5
array_1d = np.arange(1, 6)
print(f"B. 1D Array (1 to 5):{array_1d}")
print(f"   Shape: {array_1d.shape}, Dimensions: {array_1d.ndim}")

# C. A 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d_flat = np.arange(10, 61, 10)
array_2d = array_2d_flat.reshape(2, 3)
print(f"C. 2D Array (2x3, 10 to 60 in steps of 10):{array_2d}")
print(f"   Shape: {array_2d.shape}, Dimensions: {array_2d.ndim}")

A. Scalar:5
   Shape: (), Dimensions: 0
B. 1D Array (1 to 5):[1 2 3 4 5]
   Shape: (5,), Dimensions: 1
C. 2D Array (2x3, 10 to 60 in steps of 10):[[10 20 30]
 [40 50 60]]
   Shape: (2, 3), Dimensions: 2


9. Generate a 4x4 NumPy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
import numpy as np

# Syntax: np.random.randint(low, high, size) where 'high' is exclusive
random_array = np.random.randint(0, 101, size=(4, 4))
print(f"4x4 Array of random integers (0 to 100):{random_array}")

4x4 Array of random integers (0 to 100):[[42 45 91 15]
 [59  6 25 31]
 [85 15 70 94]
 [66 59 77 89]]


10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
import numpy as np
import pandas as pd

# A. Create a 2D numpy array of shape (3x3)
np_array_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f"Original numpy 2D Array (3x3):{np_array_3x3}")

# B. Convert to a pandas DataFrame and add column names
column_names = ['A', 'B', 'C']
df_from_numpy = pd.DataFrame(np_array_3x3, columns=column_names)

print("Converted Pandas DataFrame:")
print(df_from_numpy)

Original numpy 2D Array (3x3):[[1 2 3]
 [4 5 6]
 [7 8 9]]
Converted Pandas DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


#Section C: Exploring Pandas

Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:

* Use .info(), .describe()

* Select 'Name' and 'City' columns

* Drop 'City' column

* Fill any missing values in 'Salary' column with the mean

* Remove any duplicate rows

In [ ]:
import pandas as pd
import numpy as np

# A. Create a small DataFrame manually with 10 rows
data = {
    'Name': ['Jems', 'Berlin', 'Sanu', 'Will', 'Raki', 'Arun', 'Jon', 'Pinkman', 'Walter', 'Fring'],
    'Age': [25, 30, 35, 22, 28, 40, 25, 32, 22, 28],
    'City': ['NY', 'SA', 'Chi', 'NY', 'LA', 'RSA', 'USA', 'NY', 'LA', 'CAN'],
    'Salary': [70000, 80000, 120000, 65000, np.nan, 90000, 70000, 85000, np.nan, 100000]
}
df = pd.DataFrame(data)
print("Initial DataFrame")
print(df)

# 1. Use .info()
print("\n 1. DataFrame Info")
df.info()

# 2. Use .describe()
print("\n 2. DataFrame Description")
print(df.describe())

# 3. Select 'Name' and 'City' columns
print("\n 3. Selected Columns ('Name', 'City')")
selected_cols = df[['Name', 'City']]
print(selected_cols)

# 4. Drop 'City' column
df.drop('City', axis=1, inplace=True)
print("\n 4. DataFrame after Dropping 'City' Column")
print(df)

# 5. Fill any missing values in 'Salary' column with the mean
salary_mean = df['Salary'].mean()
df['Salary'].fillna(salary_mean, inplace=True)
print(f"\n 5. DataFrame after Filling Missing 'Salary' (Mean: {salary_mean:.2f})")
print(df)

# 6. Remove any duplicate rows
df.drop_duplicates(inplace=True)
print("\n 6. DataFrame after Removing Duplicate Rows")
print(df)

Initial DataFrame
      Name  Age City    Salary
0     Jems   25   NY   70000.0
1   Berlin   30   SA   80000.0
2     Sanu   35  Chi  120000.0
3     Will   22   NY   65000.0
4     Raki   28   LA       NaN
5     Arun   40  RSA   90000.0
6      Jon   25  USA   70000.0
7  Pinkman   32   NY   85000.0
8   Walter   22   LA       NaN
9    Fring   28  CAN  100000.0

 1. DataFrame Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

 2. DataFrame Description
             Age         Salary
count  10.000000       8.000000
mean   28.700000   85000.000000
std     5.755191   18322.507626
min    22.000000   65000.000000
25%    25.000000   70000.000000
50%    28.00

/tmp/ipython-input-561009253.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(salary_mean, inplace=True)
